site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - Home: index.md
    - User Guide:
      - Creating an app: creating.md
      - Running: running.md
      - Responses: responses.md
      - Parameters: parameters.md
      - Documenting Your App: docs.md
      - Reference: reference.md
    - Development Guide:
      - Home: dev/welcome.md
      - Workflow: dev/workflow.md

theme:
    name: null
    custom_dir: "html/"

markdown_extensions:
  - admonition

plugins:
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]
