site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - Home: index.md
    - User Guide:
      - Getting Started:
          - Installation: installation.md
          - Configuration: configuration.md
          - Project Creation: creating_a_project.md
      - Building Projects:
          - App Basics: app_basics.md

theme:
    name: null
    custom_dir: "html/"

markdown_extensions:
  - admonition

plugins:
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]
