site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - Home: index.md
    - Creating an app: creating.md
    - Running: running.md
    - Responses: responses.md
    - Parameters: parameters.md

theme:
    name: null
    custom_dir: "html/"

markdown_extensions:
  - admonition
