[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "my_app"
authors = [
    {name = "aryaman", email = "your@email.com"}
]
requires-python = ">=3.7"
license = "MIT"
dependencies = ["view.py", "uvicorn"]
version = "1.0.0"
